version: "3"
services:
  valorant-app:
    image: ghcr.io/thomasdissert/valorant-profile-checker:main
    container_name: valorant-app
    networks:
      - valorant-network
    ports:
      - 12001:3000/tcp
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://valorant-redis:6379
      - BASE_URL=https://valorant.thomasdissert.com
  valorant-redis:
    image: redis:6.2-alpine
    container_name: valorant-redis
    networks:
      - valorant-network
    restart: unless-stopped
    
networks:
  valorant-network:
    driver: bridge