version: "3"
services:
  valorant-app:
    image: ghcr.io/thomasdissert/valorant-profile-checker:main
    container_name: valorant-app
    network_mode: bridge
    ports:
      - 12001:3000/tcp
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_REDIS_URL=redis://valorant-redis:46379
      - NEXT_PUBLIC_BASE_URL=https://valorant.thomasdissert.com
  valorant-redis:
    image: redis:6.2-alpine
    container_name: valorant-redis
    network_mode: bridge
    ports:
      - '46379:6379'
    restart: unless-stopped
  